### ISSUE TITLE
[오타] 목차 10.1.3 오타가 있어 공유 드립니다!

### ISSUE THREAD

**Issue by 0r0loo** [wikibook/react-deep-dive-example#1]
<img width="650" alt="image" src="https://github.com/wikibook/react-deep-dive-example/assets/49504411/48b23c83-1446-4065-8a30-dd65c44f17dc">

__10.1.3 import React from ‘**reac**’가 더 이상 필요 없다: 새로운 JSX transform

=>

__10.1.3 import React from ‘**react**’가 더 이상 필요 없다: 새로운 JSX transform

**Comment by wikibook** [comment]
@0r0loo 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 확인했는데 목차에서 해당 부분을 말씀하신 대로 수정해야 맞습니다. 해당 사항은 오탈자란에 등록하고, 다음 인쇄 때 반영하도록 하겠습니다. 번거롭게 해드려 죄송하고, 꼼꼼하게 확인해 주셔서 감사합니다!

오늘도 좋은 하루 보내세요.
고맙습니다.

**Comment by yceffort** [comment]
ㅠ_ㅠ 오타 발견해주셔서 정말 감사합니다. 검수때 꼼꼼하게 확인했어야 했는데 제 불찰입니다. 다음 인쇄 때 수정토록 하겠습니다.

감사합니다.
