### ISSUE TITLE
[문의] 초판 174p, 175p 내용 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#10]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 2.4.2 리액트의 렌더링이 일어나는 이유

페이지 : 174p
내용 :
'... 두 트리 사이에서 통일한 key를 가지고 ...' 라는 문장이 있는데 혹시 '통일한'이 아니라 '동일한'이 아닐지 하여 여쭤봅니다. 근데 '통일한'도 뜻이 통하는 것 같긴합니다.

페이지 : 175p
내용 :
'만약 반대로 key에 ...'로 시작하는 문단이 연속되어 나오고 있습니다. 제 느낌상으로는 처음 나오는 문단이 초안이고 후술된 문단이 최종 수정하신 원고시지 않을까 감히 예상해봅니다. 

P.S. 오타나 순간 흐름이 갸웃한 경우 고민하다 이렇게 이슈를 생성했었는데 코멘트 남겨주셔서 감사합니다.
절대 꼼꼼히 확인하지 않으셨다고 생각하지 않으며, 이런 방대한 책을 집필하신 것에 대해 대단하시다고 느껴지는 마음 뿐입니다.
이렇게나마 도움이 된다면 기쁠 것 같습니다. 감사합니다.

**Comment by wikibook** [comment]
@dearlsh94 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 확인했는데 두 내용 모두 편집 과정에서 꼼꼼하게 확인하지 못해서 생긴 오류입니다.  제보해 주신 내용은 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 등록했습니다.

- 174쪽, 본문 밑에서 2번째 줄
    `통일한` key를 가지고 있는
     ==>
    `동일한` key를 가지고 있는

- 175쪽, 본문 4번째 줄(중복된 단락 중 첫 번째 단락 삭제)
    `만약 반대로 key에 <Child index={Math.random()} />과 같이 매 렌더링마다 변하는 임의의 값을 넣는다고 가정해 보자. 이는 리렌더링이 일어날 때마다 sibling 컴포넌트를 명확히 구분할 수 없어 Child가 memo로 선언됐더라도 매번 리렌더링이 일어나게 된다. 즉, key의 변화는 리렌더링을 야기한다.`
    만약 반대로 `<Child key={Math.random()} />`과 같이 렌더링할 때마다 변하는 임의의 값을 key에 넣는다고 가정해 보자. 이때는 리렌더링이 일어날 때마다 sibling 컴포넌트를 명확히 구분할 수 없으므로 Child는 memo로 선언됐더라도 매번 리렌더링이 일어나게 된다. 즉, key의 변화는 리렌더링을 야기한다. 이러한 특징을 이용하면 key를 활용해 강제로 리렌더링을 일으키는 것이 가능해진다.
    ==>
    `(삭제)`
    만약 반대로 `<Child key={Math.random()} />`과 같이 렌더링할 때마다 변하는 임의의 값을 key에 넣는다고 가정해 보자. 이때는 리렌더링이 일어날 때마다 sibling 컴포넌트를 명확히 구분할 수 없으므로 Child는 memo로 선언됐더라도 매번 리렌더링이 일어나게 된다. 즉, key의 변화는 리렌더링을 야기한다. 이러한 특징을 이용하면 key를 활용해 강제로 리렌더링을 일으키는 것이 가능해진다.

불편을 드려 죄송하고요, 번거로우실 텐데 이렇게 제보해 주신 내용이 더 나은 책이 되는 데 무척 큰 도움이 되고 있습니다...! 제보해 주신 내용은 다음 인쇄 때 반영하도록 하겠습니다.

그럼 오늘도 즐겁고 편안한 하루 보내세요!
고맙습니다.

**Comment by yceffort** [comment]
확인해주셔서 감사합니다. 다음 인쇄 때 꼭 반영하도록 하겠습니다. 감사합니다!!
