### ISSUE TITLE
[문의] 초판 320p 오타 문의드립니다

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#13]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 4.3.3 Data Fetching
페이지 : 320p
내용 :
320p 하단 문단의 내용 중 "즉, getInitalProps는 라우팅에 따라서 서버와 클라이언 모두에서 실행 가능한 메서드인 것이다."의 내용 중 "클라이언"이 "클라이언트"의 오타가 아닌지 해서 문의드립니다.

감사합니다.

**Comment by yceffort** [comment]
넵 말씀해주신 내용은 오타가 맞습니다. 확인해주셔서 감사합니다! 
위 내용은 2쇄에 반영하도록 하겠습니다. 감사합니다!

**Comment by wikibook** [comment]
@dearlsh94 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셔서 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 등록했습니다.

- 320쪽, 본문 밑에서 4번째 줄
    따라서 서버와 `클라이언` 모두에서
    ==>
    따라서 서버와 `클라이언트` 모두에서

불편을 드려 죄송하고요, 제보해 주신 내용은 다음 인쇄 때 반영하도록 하겠습니다.

그럼 오늘도 즐겁고 편안한 하루 보내세요!
고맙습니다.
