### ISSUE TITLE
[문의] 초판 331p 내용 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#14]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 4.3.5 _app.tsx 응용하기
페이지 : 331p
내용 :
하단 예시로 작성해주신 코드 내용 중 `return appProps` 부분이 있는데 `appProps`가 선언되어 있지 않은 것 같습니다. 이전의 예시에서는 `const appProps = await App.getInitialProps`가 확인되는데, 혹 추가되어야 하는 것은 아닌지 하여 문의드립니다.

연말 약속들을 보내고 다시 잘 읽고 있습니다.
감사합니다.

**Comment by yceffort** [comment]
@dearlsh94 님, 번번히 도움 받고 있네요. 감사합니다 ㅠ_ㅠ
말씀해주신대로 331번쨰 코드예제의 두번째 줄에 이전 페이지에 있는

```javascript
const appProps = await App.getInitialProps
```

가 추가되는 것이 맞습니다. 이부분도 수정하도록 하겠습니다. 감사합니다!

**Comment by wikibook** [comment]
@dearlsh94 님, 위키북스 담당자입니다.

제보해 주신 이 내용도 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 등록했습니다.

- 331쪽, 페이지 하단 예제 코드의 2번째 줄(코드 추가)
    ~~~
    const {
    ~~~
    ==>
    ~~~
    const appProps = await App.getInitialProps(context)
    const {
    ~~~

불편을 드려 죄송하고요, 번거로우실 텐데 이렇게 제보해 주셔서 감사드립니다. 제보해 주신 내용은 다음 인쇄 때 반영하도록 하겠습니다.
고맙습니다.
