### ISSUE TITLE
[ 오타문의 ] [초판] 301p 오타문의입니다.

### ISSUE THREAD

**Issue by supersfel** [wikibook/react-deep-dive-example#15]
간단한 오탈자 오류입니다.
```
gretting -> greeting
```
총 2개 바꿔야 할 것 같습니다!

**Comment by wikibook** [comment]
@supersfel 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 확인했는데, 오탈자로 확인되어 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 등록했습니다.

- 301쪽, 본문 밑에서 6번째 줄
    `gretting` 변수에는 각각 1, `greetting`이라는 값이 들어온다. 
    ==>
    `greeting` 변수에는 각각 1, `greeting`이라는 값이 들어온다. 

제보해 주셔서 감사드리고요, 해당 내용은 다음 인쇄 때 반영하도록 하겠습니다.
그럼 오늘도 즐거운 하루 보내세요!
고맙습니다.
