### ISSUE TITLE
[문의] 초판 372p 오타 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#16]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 5.2.4 상태 관리 라이브러리 Recoil, Jotai, Zustand 살펴보기
페이지 : 372p
내용 : 
두번 째 문단의 시작 부분에서 "Recoil과 Jotai는 Context과 Provider, ..." 라는 문장이 있습니다. 해당 페이지의 상단 부분에서는 "Context와"라고 하신 것으로 보아 "Context과"가 오타가 아닌 지 해서 문의 드립니다.

흥미롭게 잘 읽고 있습니다. 항상 감사드립니다.
2024년 새해 복 많이 받으세요.

**Comment by yceffort** [comment]
오타 제보해주셔서 감사합니다. 오타가 많아서 조금 민망할 정도네요 ㅠ_ㅠ!
2쇄에 반영하도록 하겠습니다. 

감사합니다. 따뜻한 연말되세요:)

**Comment by wikibook** [comment]
@dearlsh94 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 오탈자로 등록했습니다.

- 372쪽, 본문 밑에서 5번째 줄
    Recoil과 Jotai는 Context`과` Provider,
    ==>
    Recoil과 Jotai는 Context`와` Provider,

꼼꼼하게 확인해 주셔서 감사드리고요, 해당 내용은 다음 인쇄 때 반영하도록 하겠습니다.
그럼 오늘도 편안한 밤 보내시고, 즐거운 주말 맞이하시기 바랍니다.
고맙습니다.
