### ISSUE TITLE
[문의] 초판 412p 내용 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#17]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 6.3 리액트 개발 도구 활용하기
페이지 : 412p
내용 :
페이지 상단 설명 내용 중 "위 화면에서는 2번째 줄 어딘가에 해당 소스 코드가 존재하는 것은 사실이지만 2번째 행은 13만 줄이라 사람이 확인하는 것이 불가능하다." 라는 문장에서, 13만 줄이라는 말이 혹 13만 열이 아닌가해서 문의드립니다.

이제 절반을 향해 달려가고 있습니다!
감사합니다.

**Comment by yceffort** [comment]
넵 맞습니다! 이 오타 내용도 수정될 수 있도록 하겠습니다. 

@wikibook 님, 이 내용 3쇄에 반영될 수 있을까요?

**Comment by wikibook** [comment]
@dearlsh94 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 오탈자로 등록했습니다.

- 412쪽, 본문 2번째 줄
    2번째 행은 13만 `줄`이라
    ==>
    2번째 행은 13만 `열`이라

꼼꼼하게 확인해 주셔서 감사드리고요, 해당 내용은 다음 3쇄 인쇄할 때 반영하도록 하겠습니다.
그럼 오늘도 잘 마무리하시고, 즐거운 주말 맞이하시기 바랍니다.
고맙습니다.

**Comment by wikibook** [comment]
@yceffort 님, 확인 감사합니다.

독자분께서 제보해 주신 내용은 3쇄에 반영하겠습니다.
감사합니다..!
