### ISSUE TITLE
[문의][초판] p.363 ,p.367 문의

### ISSUE THREAD

**Issue by supersfel** [wikibook/react-deep-dive-example#18]
간단한 문의입니다! 새해복 많이 받으세요 ㅎㅎ

p.363
```typescript
function TextEditor() {
  const text = useStoreSelector(store, textSelector);
  useEffect(() => console.log("Counter Rendered")); //"TextEditor Rendered" 가 더 어울릴 듯 합니다.

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    store.set((prev) => ({ ...prev, text: e.target.value }));
  }

  return (
    <>
      <h3>{text}</h3>
      <input value={text} onChange={handleChange}></input>
    </>
  );
}
```

---

p.367 
리액트 18버전의 useSubscription을 살펴보면 useSubscription 훅 자체가 useSyncExternalStore로 "재작" <-- "제작" 오타 난것 같습니다.

**Comment by yceffort** [comment]
흡 ㅠㅠ 맞습니다. 저거 예제 고치는 과정에서 잘못되었던 것 같습니다. 두 오타 모두 수정하도록 하겠습니다.

**Comment by wikibook** [comment]
@supersfel 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셔서 첫 번째 내용에 대해 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 오탈자로 등록했습니다.

- 363쪽, 예제 코드의 18번째 줄
    ~~~
    console.log('Counter Rendered')
    ~~~
    ==>
    ~~~
    console.log('TextEditor Rendered')
    ~~~

추가로 제보해 주신 367쪽 내용의 경우 '재작성돼 있는 것을'이라는 표현인데요, 여기서는 재작성(rewrite)를 의미하기 때문에 오탈자로 보기는 어렵습니다.

그럼 참고 부탁드리고요, 해당 내용은 다음 인쇄 때 반영하도록 하겠습니다.
오늘도 잘 마무리하시고, 즐거운 주말 맞이하시기 바랍니다.
고맙습니다.
