### ISSUE TITLE
[문의] 예제 질문입니다.

### ISSUE THREAD

**Issue by 01-binary** [wikibook/react-deep-dive-example#2]
안녕하세요!
챕터 3은 리액트 훅 깊게 살펴보기로 알고 있는데
예제의 챕터3에는 nextjs랑 ssr 예시 코드가 있습니다.

전반적으로 책의 Chapter랑 예제랑 맞지 않는 것 같아 질문드립니다. 🙏

**Comment by yceffort** [comment]
@01-binary 님 안녕하세요! 책 저자입니다 :)
책 발간을 앞두고 챕터별로 분량이 길다는 의견이 있어서 막판에 챕터를 분리했었는데,
예제 코드의 폴더 구성에는 그 내용이 반영되지 않은 것 같습니다.
꼼꼼하게 챙기지 못해서 죄송합니다.
해당 이슈는 제가 금주 중으로 수정해두겠습니다. 

책과 코드 모두 관심있게 봐주셔서 감사합니다. 
편안한밤되세요 =)

**Comment by 01-binary** [comment]
아닙니다~! 빠른 피드백 감사드립니다.
책 정말 재밌게 읽고있어요
좋은 책 써주셔서 감사합니다 ~ 🙏

**Comment by yceffort** [comment]
@01-binary 님, 의견 주셔서 정말 감사합니다. 말씀하신대로 챕터 책과 맞게 수정완료하였습니다. 
감사합니다 좋은하루되세요 :D
