### ISSUE TITLE
[문의] p202 내용 문의 드립니다.

### ISSUE THREAD

**Issue by youdame** [wikibook/react-deep-dive-example#21]
useEffect 밖과 안에서 console.log("렌더링 됨")을 출력하는 경우를 비교하는 부분에 대한 설명이 아래와 같이 적혀있습니다.

<내용>
1.  이후에 소개할 서버 사이드 렌더링 관점에서 useEffect는 클라이언트 사이드에서 실행되는 것을 보장해 준다. useEffect 내부에서는 window 객체의 접근에 의존하는 코드를 사용해도 된다.

2.  useEffect는 컴포넌트 렌더링의 부수 효과, 즉 컴포넌트의 렌더링이 완료된 이후에 실행된다. 반면 직접 실행은 컴포넌트가 렌더링되는 도중에 실행된다. 따라서 1번과는 달리 서버 사이드 렌더링의 경우에 서버에서도 실행된다. 그리고 이 작업은 함수형 컴포넌트의 반환을 지연시키는 행위다. 즉. 무거운 작업일 경우 렌더링을 방해하므로 성능에 악영향을 미칠 수 있다.

<문의> 
문의 드릴 부분은 2의 내용입니다. 따라서 "1번과 달리"가 아니라 "2번과 달리"가 맞는 표현 아닌가요? 

<이유>
2번이 useEffect 안에서 console.log("렌더링 됨") 실행하는 경우이니까요. 

<추가 문의>
또한 "직접 실행"이라는 말이 너무 모호하게 느껴집니다. 처음에 이해를 못했는데 1번의 경우(1. useEffect 밖에서  console.log("렌더링 됨") 실행)를 의미하더라구요.

**Comment by yceffort** [comment]
안녕하세요, 김용찬입니다. 
먼저 문의 남겨주셔서 감사합니다.  답변 드리도록 하겠습니다.

>  문의 드릴 부분은 2의 내용입니다. 따라서 "1번과 달리"가 아니라 "2번과 달리"가 맞는 표현 아닌가요?

넵 맞습니다. 2번과는 달리로 고치는게 맞습니다. 이부분은 오타인 것 같네요 ㅠㅠ 수정하도록 하겠습니다.

>  또한 "직접 실행"이라는 말이 너무 모호하게 느껴집니다. 처음에 이해를 못했는데 1번의 경우(1. useEffect 밖에서 console.log("렌더링 됨") 실행)를 의미하더라구요.

직접 실행이 함수 자체가 직접 실행하는 경우를 말하는 것이었는데, 말씀하신 대로 조금 이해가 어려우실수 있을 것 같습니다.

반면 1번과 같이 함수 내부에서의 직접 실행은 ~

으로 고치도록 하겠습니다.

제보해주셔서 정말 감사합니다. 말씀하신 내용은 꼭 반영 토록 하겠습니다.

**Comment by wikibook** [comment]
@youdame 님, 안녕하세요.
위키북스 담당자입니다.

제보해 주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 등록했습니다.

- 202쪽, 본문 8번째 줄
    반면 `직접 실행은` 컴포넌트가 렌더링되는 도중에 실행된다. 따라서 `1`번과는 달리 
    ==>
    반면 `1번과 같이 함수 내부에서의 직접 실행은` 컴포넌트가 렌더링되는 도중에 실행된다. 따라서 `2`번과는 달리 

저희 책을 꼼꼼하게 읽어주셔서 감사드리고요, 해당 내용은 다음 인쇄 때 반영하도록 하겠습니다.
고맙습니다.
