### ISSUE TITLE
[문의] p.24 예제 문의드립니다.

### ISSUE THREAD

**Issue by hayamaster** [wikibook/react-deep-dive-example#22]
인쇄일 : 초판발행 2023년 11월 07일
목차 : 1.1.1 자바스크립트의 데이터 타입
페이지 : 24p
내용 : 
2진수, 8진수, 16진수 동등 비교 예제에 주석 설명이 맞지 않은 것 같아 문의 드립니다.
```typescript
const 이진수_2 = 0b10 // 2진수 (binary) 2
이진수_2 == (2).toString(2) // true (2)를 괄호로 선언한 이유는 2뒤에 점이 있으면 소수점으로 인식하기 때문

const 팔진수_8 = 0o10 // 8진수 (octal) 8
팔진수_8 == (8).toString(8) // true
...
```
`0b10`의 값은 2가 맞지만, 동등 비교식에 `(2).toString(2)`은 숫자 2를 2진수로 변경하라는 뜻으로 결과가 '10'이 될 것 같습니다.
마찬가지로 `0o10`의 값은 8이지만 `(8).toString(8)`은 숫자 8을 8진수로 변경하기에 '10'이 될 것 같습니다.
추가되는 16진수 또한 같은 문제점을 가지고 있습니다. 
이에 비교 값이 'true'가 아닌 'false'가 되어야 할 것 같다고 생각되었습니다.

**Comment by yceffort** [comment]
안녕하세요~ 김용찬입니다.
먼저 책에 관심 가져주셔서 감사합니다 ㅠㅠ

제가 이거 작성하다가 너무 큰 실수를 저지른 것 같아 송구합니다.
말씀하신 내용이 맞구요.

```js
const 이진수_2 = 0b10 // 2진수(binary) 2
이진수_2 === 2

const 팔진수_8 = 0o10 // 8진수(octal) 8
팔진수_8 === 8

const 십육진수_16 = 0x10 // 16진수(hexadecimal) 16
십육진수_16 === 16 // true
```

으로 수정되는게 맞는 것 같습니다. cc) @wikibook  
이부분 수정해서 반영하도록 하겠습니다. 감사합니다!

**Comment by wikibook** [comment]
@hayamaster 님, 안녕하세요.
위키북스 담당자입니다.

저자분께서 제보해 주신 내용을 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)에 다음과 같이 등록했습니다.

- 24쪽, 페이지 중간 예제 코드를 다음 예제로 교체
    ~~~
    const 이진수_2 = 0b10 // 2진수(binary) 2
    이진수_2 == 2 // true

    const 팔진수_8 = 0o10 // 8진수(octal) 8
    팔진수_8 == 8 // true

    const 십육진수_16 = 0x10 // 16진수(hexadecimal) 16
    십육진수_16 == 16 // true
    ~~~

제보해 주셔서 감사드리고요, 해당 내용은 다음 인쇄 때 반영하도록 하겠습니다.
고맙습니다.
