### ISSUE TITLE
[문의] 초판 29p 오타문의

### ISSUE THREAD

**Issue by honki12345** [wikibook/react-deep-dive-example#3]
초판, 29p 1.1.3 자바스크립트의 또 다른 비교 공식, Object.is 내용에서 입니다.

---

== 비교는 같음을 비교하기 전에 양쪽이 같은 타입이 아니라면 비교할 수 있도록 강제로 형변환(type casting)을 한 후에 변경한다.

-> == 비교는 같음을 비교하기 전에 양쪽이 같은 타입이 아니라면 비교할 수 있도록 강제로 형변환(type casting)을 한 후에 `비교`한다.

**Comment by yceffort** [comment]
넵 이것도 오타가 맞습니다. 수정하도록 하겠습니다. 감사합니다.

**Comment by wikibook** [comment]
@honki12345 님, 
위키북스 담당자입니다.
앞서 32쪽 오류와 함께 코멘트를 드렸는데요, 확인 부탁드립니다..!
고맙습니다.
