### ISSUE TITLE
[문의] 초판 32p 예제문의

### ISSUE THREAD

**Issue by honki12345** [wikibook/react-deep-dive-example#4]
초판, 32p 예제에 대한 문의입니다

---

```typescript
type Props = {
  hello: string
}

function HelloComponent(props: Props) {
  return <h1>{hello}</h1>
}
// ...
function App() {
  return <HelloComponent hello="hi!"/>
}
```

  return \<h1>{hello}\</h1>
->   return \<h1>{props.hello}\</h1>

**Comment by yceffort** [comment]
앗 이건 말씀해주신대로 잘못된 코드입니다. 수정하도록 하겠습니다. 감사합니다.

**Comment by wikibook** [comment]
@honki12345 님, 안녕하세요.
위키북스 담당자입니다.

29, 32쪽과 관련해서 제보해 주신 두 가지 내용을 모두 저자분께서 확인해 주셔서 홈페이지 정오표란에 등록했습니다.

https://wikibook.co.kr/react-deep-dive/

불편을 드려 죄송하고, 저희 책을 꼼꼼하게 봐주셔서 감사드립니다. 수정된 내용은 다음 인쇄 때 반영하도록 하겠습니다. 고맙습니다.
