### ISSUE TITLE
초판, 89p, 오타문의

### ISSUE THREAD

**Issue by honki12345** [wikibook/react-deep-dive-example#5]
aObj와 bObj의 결괏값은 다른데, 전개 구문 이후에 값 할당이 있다면 `전개 구문`이 `할당한 값`을 덮어쓰겠지만
-> aObj와 bObj의 결괏값은 다른데, 전개 구문 이후에 값 할당이 있다면 `할당한 값`이 `전개 구문`을 덮어쓰겠지만

**Comment by yceffort** [comment]
@honki12345 님, 오타 제보 감사합니다.

말씀해주신 의견에 맞춰 수정하는게 맞는 표현으로 보입니다.

```
전개구문이 후에 값 할당이 있다면 할당한 값이 이전에 전개했던 구문 값을 덮어쓰겠지만, 반대의 경우에는 오히려 전개구문이 해당 값을 덮어쓰는일이...
```

2판에 해당 내용 수정하도록 하겠습니다. 감사합니다.

**Comment by wikibook** [comment]
@honki12345 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 저자분께서 확인해 주셨기에 다음과 같이 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)에 등록했습니다.

- 89쪽, 본문 첫 번째 줄

    값 할당이 있다면 `전개 구문이 할당한 값을` 덮어쓰겠지만

    ==>

    값 할당이 있다면 `할당한 값이 이전에 전개했던 구문 값을` 덮어쓰겠지만

불편을 드려 죄송하고, 오류를 바로잡을 수 있게 해주셔서 감사합니다. 수정 내용은 다음 인쇄 때 반영하도록 하겠습니다.
고맙습니다.
