### ISSUE TITLE
초판 99p,102p 예제문의

### ISSUE THREAD

**Issue by supersfel** [wikibook/react-deep-dive-example#6]
99p 아래 함수에서 return  a / b 가 조금더 적절한 예시일 것 같습니다. (크게 안중요한거 같기도 합니다.)

```
function test(a,b) {
	if (typeof a !== 'number' || typeof b !== 'number'){
    	throw new Error('a와 b 모두 숫자여야 합니다.')
    }
    return 5 / 2
}
```

```
function test(a,b) {
	if (typeof a !== 'number' || typeof b !== 'number'){
    	throw new Error('a와 b 모두 숫자여야 합니다.')
    }
    return a/b
}
```

---

102p 아래 예시의 함수는 function이 들어와도 에러가 무조건 발생하게 되어 if문안에 return이 들어가야 할 것 같습니다.
```
function doSomething(callback : unknown) {
	if (typeof callback === 'function') {
    	callback()
    }
    throw new Error('callback은 함수여야 합니다')
}
```

```
function doSomething(callback : unknown) {
	if (typeof callback === 'function') {
    	callback()
        return
    }
    throw new Error('callback은 함수여야 합니다')
}

doSomething(() => {console.log('hello')})
```

**Comment by yceffort** [comment]
안녕하세요! 책 관심깊게 읽어주셔서 감사합니다.

1. 말씀해주신대로 첫번째 내용은 설명에 있어 크게 중요한 부분은 아니지만, 제 실수가 맞습니다. 수정하도록 하겠습니다.
2. 맞습니다. 말씀하신대로 `return` 문이 누락되었습니다.

위 두 내용 다음 발행 때 수정하도록 하겠습니다. 감사합니다.

**Comment by wikibook** [comment]
@supersfel 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 제보해 주신 내용을 등록했습니다.

- 99쪽, 2번째 예제 코드의 5번째 줄
    ~~~
    return 5 / 2
    ~~~
    ==>
    ~~~
    return a / b
    ~~~

- 102쪽, 2번째 예제 코드의 3번째 줄
    ~~~
    callback()
    ~~~
    ==>
    ~~~
    callback()
    return
    ~~~

불편을 드려 죄송하고요, 해당 사항은 다음 인쇄 때 반영하도록 하겠습니다. 저희 책을 꼼꼼하게 확인해 주셔서 감사합니다!

그럼 오늘도 좋은 하루 보내세요.
고맙습니다.
