### ISSUE TITLE
초판, 123p, 예제문의

### ISSUE THREAD

**Issue by honki12345** [wikibook/react-deep-dive-example#7]
123p 에 `[코드2.2] 유효한 형태의 JSX`의 예제에 관한 문의입니다.

---

```jsx
// 속성과 속성을 넣을 수 있다
const ComponentE = <A required={false} />
```
 `속성과 속성을 넣을 수 있다`라는 표현에 대한 문의입니다.
속성과 속성이 아닌
-> 속성과 `속성값`을 넣을 수 있다
라는 의미로 쓰신건지 궁금해서 문의드립니다

**Comment by yceffort** [comment]
안녕하세요. 계속해서 오타 제보해주셔서 송구하고 🥲 감사합니다.

말씀하신대로 `속성과 속성값을 넣을 수 있다` 로 수정되어야 합니다.
제 불찰입니다.

제안해주신 내용 수정하도록 하겠습니다.
감사합니다.

**Comment by wikibook** [comment]
@honki12345 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 제보해 주신 내용을 등록했습니다.

- 123쪽, 예제 코드의 6번째 줄
    ~~~
    // 속성과 속성을 넣을 수 있다.
    ~~~
    ==>
    ~~~
    // 속성과 속성값을 넣을 수 있다.
    ~~~

불편을 드려 죄송하고요, 해당 사항은 다음 인쇄 때 반영하도록 하겠습니다. 저희 책을 꼼꼼하게 확인해 주셔서 감사합니다!

그럼 오늘도 좋은 하루 보내세요.
고맙습니다.

**Comment by honki12345** [comment]
책 잘 보고 있습니다. 스터디를 하며 공부하고 있어요.
요새 온라인 강의를 많이 찍고 개발서적 하나가 귀한데 이렇게 좋은 책 집필해주셔서 감사합니다.
보고 많이 배우고 있습니다.

**Comment by yceffort** [comment]
@honki12345 님 안녕하세요!

메일로 인사드리고 싶었는데, 메일 주소를 찾지 못해 깃헙 댓글로 연락드립니다.

책에 많은 관심가져주셔서 정말 감사합니다.
장기간 꽤 열심히 썼다고 생각했고, 또 잘못된 부분도 거의 없을 것이라고 생각했는데
첫 저서이다보니 아무래도 부족한점이 너무 많았던 것 같습니다.
책 내용 꼼꼼하게 확인해주시고 또 제보해주셔서 감사합니다.

다름이 아니고 제보해주신 내용을 수정한 2쇄를 곧 인쇄할 예정인데요.
그리고 이 수정된 2쇄 본을 감사의 마음을 담아 @honki12345 님께 전달해드리고 싶습니다.

혹시 실례가 되지 않는다면 택배를 받으실 수 있는 주소를 제 메일 root@yceffort.kr 로 알려주실수 있을까요?
전달과 인쇄에는 수일이 소요 되어 올해내로 받는 것은 쉽지 않아 보이지만,
늦더라도 꼭 전해드리고 싶습니다.

감사합니다.

**Comment by honki12345** [comment]
헉 좋게 봐주셔서 감사합니다.
고작 이런 일로 책 받는게 너무 송구스럽지만
너무 기쁜 마음에 주소 메일로 보내드렸습니다.
감사합니다 :)
