### ISSUE TITLE
[문의] 초판 118p 예시 내용 오타 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#8]
- 인쇄일 : 초판발행 2023년 11월 07일
- 목차 : 2.1.1 JSX의 정의
- 페이지 : 118p
- 내용 :
JSXElement에 대해 설명해주시는 내용 중 JSXClosingElement의 설명에 대한 예시로 작성된 `<JSXElement />`에 대해 문의 드립니다.
이 예시 문법은 JSXSelfClosingElement에 어울리는 예시로, JSXClosingElement에서는 `</JSXElemnt>`와 같이 되어야 하지 않을 지 문의드립니다.

책 너무 잘 읽고 있습니다. 
출판해주셔서 감사합니다.

**Comment by yceffort** [comment]
안녕하세요. 오타제보해주셔서 정말 감사합니다.

말씀하신대로 `</ JSXElement>` 가 되는게 맞습니다.
지적해주신 내용 다음 출판때 수정하도록 하겠습니다.

정말 감사합니다.

**Comment by wikibook** [comment]
@dearlsh94 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 제보해 주신 내용을 등록했습니다.

- 118쪽, 본문 6번째 줄
    ~~~
    - 예: <JSXElement />
    ~~~
    ==>
    ~~~
    - 예: </JSXElement>
    ~~~

불편을 드려 죄송하고요, 해당 사항은 다음 인쇄 때 반영하도록 하겠습니다. 꼼꼼하게 확인해 주시고 또 번거로우셨을 텐데 출판사에 제보해 주셔서 감사합니다!

그럼 오늘도 좋은 하루 보내세요.
고맙습니다.
