### ISSUE TITLE
[문의] 초판 133p 내용 오타 문의드립니다.

### ISSUE THREAD

**Issue by dearlsh94** [wikibook/react-deep-dive-example#9]
- 인쇄일 : 초판발행 2023년 11월 07일
- 목차 : 2.2.3 가상 DOM을 위한 아키텍처, 리액트 파이버
- 페이지 : 133p
- 내용 :
리액트 파이버에 대한 설명 중 '과거 리액트 리액트의 조정 알고리즘은 스택 알고리즘으로 이뤄져 있었다.' 라는 문장이 있습니다. 혹, "리액트 리액트"가 아닌 "리액트"를 의도하신 건 아니신지 해서 오타 문의드립니다.

감사합니다.

**Comment by yceffort** [comment]
안녕하세요. 제보해주셔서 감사합니다. 
말씀해주신  내용도 오타가 맞습니다. (ㅠㅠ)
꼼꼼하게 확인하지 못하여 죄송하며, 다음번 출판때 수정하도록 하겠습니다. 감사합니다.

**Comment by wikibook** [comment]
@dearlsh94 님, 

이 내용 또한 저자분께서 확인해 주셨기에 [홈페이지 정오표](https://wikibook.co.kr/react-deep-dive/)란에 다음과 같이 제보해 주신 내용을 등록했습니다.

- 133쪽, 본문 밑에서 7번째 줄
    과거 `리액트 리액트의` 조정 알고리즘은
    ==>
    과거 `리액트의` 조정 알고리즘은

불편을 드려 죄송하고요, 해당 사항은 다음 인쇄 때 반영하도록 하겠습니다. 
감사합니다..!
